uint8 FX_EFFECT_STATIC                   = 0
uint8 FX_EFFECT_BLINK                    = 1
uint8 FX_EFFECT_BREATH                   = 2
uint8 FX_EFFECT_COLOR_WIPE               = 3
uint8 FX_EFFECT_COLOR_WIPE_INV           = 4 
uint8 FX_EFFECT_COLOR_WIPE_REV           = 5
uint8 FX_EFFECT_COLOR_WIPE_REV_INV       = 6
uint8 FX_EFFECT_COLOR_WIPE_RANDOM        = 7
uint8 FX_EFFECT_RANDOM_COLOR             = 8
uint8 FX_EFFECT_SINGLE_DYNAMIC           = 9
uint8 FX_EFFECT_MULTI_DYNAMIC           = 10
uint8 FX_EFFECT_RAINBOW                 = 11
uint8 FX_EFFECT_RAINBOW_CYCLE           = 12
uint8 FX_EFFECT_SCAN                    = 13
uint8 FX_EFFECT_DUAL_SCAN               = 14
uint8 FX_EFFECT_FADE                    = 15
uint8 FX_EFFECT_THEATER_CHASE           = 16
uint8 FX_EFFECT_THEATER_CHASE_RAINBOW   = 17
uint8 FX_EFFECT_RUNNING_LIGHTS          = 18
uint8 FX_EFFECT_TWINKLE                 = 19
uint8 FX_EFFECT_TWINKLE_RANDOM          = 20
uint8 FX_EFFECT_TWINKLE_FADE            = 21
uint8 FX_EFFECT_TWINKLE_FADE_RANDOM     = 22
uint8 FX_EFFECT_SPARKLE                 = 23
uint8 FX_EFFECT_FLASH_SPARKLE           = 24
uint8 FX_EFFECT_HYPER_SPARKLE           = 25
uint8 FX_EFFECT_STROBE                  = 26
uint8 FX_EFFECT_STROBE_RAINBOW          = 27
uint8 FX_EFFECT_MULTI_STROBE            = 28
uint8 FX_EFFECT_BLINK_RAINBOW           = 29
uint8 FX_EFFECT_CHASE_WHITE             = 30
uint8 FX_EFFECT_CHASE_COLOR             = 31
uint8 FX_EFFECT_CHASE_RANDOM            = 32
uint8 FX_EFFECT_CHASE_RAINBOW           = 33
uint8 FX_EFFECT_CHASE_FLASH             = 34
uint8 FX_EFFECT_CHASE_FLASH_RANDOM      = 35
uint8 FX_EFFECT_CHASE_RAINBOW_WHITE     = 36
uint8 FX_EFFECT_CHASE_BLACKOUT          = 37
uint8 FX_EFFECT_CHASE_BLACKOUT_RAINBOW  = 38
uint8 FX_EFFECT_COLOR_SWEEP_RANDOM      = 39
uint8 FX_EFFECT_RUNNING_COLOR           = 40
uint8 FX_EFFECT_RUNNING_RED_BLUE        = 41
uint8 FX_EFFECT_RUNNING_RANDOM          = 42
uint8 FX_EFFECT_LARSON_SCANNER          = 43
uint8 FX_EFFECT_COMET                   = 44
uint8 FX_EFFECT_FIREWORKS               = 45
uint8 FX_EFFECT_FIREWORKS_RANDOM        = 46
uint8 FX_EFFECT_MERRY_CHRISTMAS         = 47
uint8 FX_EFFECT_FIRE_FLICKER            = 48
uint8 FX_EFFECT_FIRE_FLICKER_SOFT       = 49
uint8 FX_EFFECT_FIRE_FLICKER_INTENSE    = 50
uint8 FX_EFFECT_CIRCUS_COMBUSTUS        = 51
uint8 FX_EFFECT_HALLOWEEN               = 52
uint8 FX_EFFECT_BICOLOR_CHASE           = 53
uint8 FX_EFFECT_TRICOLOR_CHASE          = 54
uint8 FX_EFFECT_TWINKLEFOX              = 55
uint8 FX_EFFECT_RAIN                    = 56
uint8 FX_EFFECT_BLOCK_DISSOLVE          = 57
uint8 FX_EFFECT_ICU                     = 58
uint8 FX_EFFECT_DUAL_LARSON             = 59
uint8 FX_EFFECT_RUNNING_RANDOM2         = 60
uint8 FX_EFFECT_FILLER_UP               = 61
uint8 FX_EFFECT_RAINBOW_LARSON          = 62
uint8 FX_EFFECT_RAINBOW_FIREWORKS       = 63
uint8 FX_EFFECT_TRIFADE                 = 64
uint8 FX_EFFECT_VU_METER                = 65
uint8 FX_EFFECT_HEARTBEAT               = 66
uint8 FX_EFFECT_BITS                    = 67
uint8 FX_EFFECT_MULTI_COMET             = 68
uint8 FX_EFFECT_FLIPBOOK                = 69
uint8 FX_EFFECT_POPCORN                 = 70
uint8 FX_EFFECT_OSCILLATOR              = 71

uint32 number

railway_interfaces/ColorRGB color
uint8 effect
uint8 brightness
uint8 effect_speed

