cv_register_descr = {
    "Short Address": 0, 
    "Vstart": 2,
    "Acceleration Rate": 3,
    "Deceleration Rate": 4,
    "Vhigh": 5,
    "Vmid": 6,
    "Manufacturer Version No.": 7,
    "Manufactured ID": 8,
    "Total PWM Period": 9,
    "EMF Feedback Cutout": 10, 
    "Packet Time-Out Value": 11,
    "Power Source Conversion": 12,
    "Alt. Mode Funct. Status F1-F8": 13, 
    "Alt. Mode Funct. Status FL,F9-F12": 14, 
    "Decoder Lock CV15": 15,
    "Decoder Lock CV16": 16,
    "Long Address (MSB)": 17,
    "Long Address (LSB)": 18,
    "Consist Address": 19,
    "Consist Addr Active for F1-F8": 21, 
    "Consist Addr Active for FL-F9-F12": 22,
    "Acceleration Adjustment": 23,
    "Deceleration Adjustment": 24,
    "Mode Control (dir, addr size, etc.)": 29,
    "Kick Start": 65,
    "Forward Trim": 66,
    "Speed Table Step 1": 67,
    "Speed Table Step 2": 68,
    "Speed Table Step 3": 69,
    "Speed Table Step 4": 70,
    "Speed Table Step 5": 71,
    "Speed Table Step 6": 72,
    "Speed Table Step 7": 73,
    "Speed Table Step 8": 74,
    "Speed Table Step 9": 75,
    "Speed Table Step 10": 76,
    "Speed Table Step 11": 77,
    "Speed Table Step 12": 78,
    "Speed Table Step 13": 79,
    "Speed Table Step 14": 80,
    "Speed Table Step 15": 81,
    "Speed Table Step 16": 82,
    "Reverse Trim": 95,
    "Extended Configuration": 97,
    "Analog Mode Function Enable": 137,
    "Function Mapping for F0-F12": 140,
    "Function Mapping for F13-F28": 141,
    "Consist Function Mapping": 142,
    "Sound Volume Control": 128,
    "Horn/Whistle Selection": 129,
    "Bell Ring Time": 130,
    "Brake Squeal Enable": 131,
    "Automatic Notching Enable": 132,
    "Lighting Effects Configuration": 133,
    "Ditch Light Flash Rate": 134,
    "Motor Control Algorithm": 135
}