ws2812_modes = [\
"STATIC",\
"BLINK",\
"BREATH",\
"COLOR WIPE",\
"COLOR WIPE INV",\
"COLOR WIPE REV",\
"COLOR WIPE REV INV",\
"COLOR WIPE RANDOM",\
"RANDOM COLOR",\
"SINGLE DYNAMIC",\
"MULTI DYNAMIC",\
"RAINBOW",\
"RAINBOW CYCLE",\
"SCAN",\
"DUAL SCAN",\
"FADE",\
"THEATER CHASE",\
"THEATER CHASE RAINBOW",\
"RUNNING LIGHTS",\
"TWINKLE",\
"TWINKLE RANDOM",\
"TWINKLE FADE",\
"TWINKLE FADE RANDOM",\
"SPARKLE",\
"FLASH SPARKLE",\
"HYPER SPARKLE",\
"STROBE",\
"STROBE RAINBOW",\
"MULTI STROBE",\
"BLINK RAINBOW",\
"CHASE WHITE",\
"CHASE COLOR",\
"CHASE RANDOM",\
"CHASE RAINBOW",\
"CHASE FLASH",\
"CHASE FLASH RANDOM",\
"CHASE RAINBOW WHITE",\
"CHASE BLACKOUT",\
"CHASE BLACKOUT RAINBOW",\
"COLOR SWEEP RANDOM",\
"RUNNING COLOR",\
"RUNNING RED BLUE",\
"RUNNING RANDOM",\
"LARSON SCANNER",\
"COMET",\
"FIREWORKS",\
"FIREWORKS RANDOM",\
"MERRY CHRISTMAS",\
"FIRE FLICKER",\
"FIRE FLICKER SOFT",\
"FIRE FLICKER INTENSE",\
"CIRCUS COMBUSTUS",\
"HALLOWEEN",\
"BICOLOR CHASE",\
"TRICOLOR CHASE",\
"TWINKLEFOX",\
"RAIN",\
"BLOCK DISSOLVE",\
"ICU",\
"DUAL LARSON",\
"RUNNING RANDOM2",\
"FILLER UP",\
"RAINBOW LARSON",\
"RAINBOW FIREWORKS",\
"TRIFADE",\
"VU METER",\
"HEARTBEAT",\
"BITS",\
"MULTI COMET",\
"FLIPBOOK",\
"POPCORN",\
"OSCILLATOR"]